site_name: "TestDocs"
site_description: "This is a test docs"
site_url: https://www.cs.cornell.edu/courses/
nav:
  - Introduction: index.md
  - External Documentation:
      - example: cs3110/2018sp/handouts/overview.html

plugins:
  - techdocs-core
